[package]
name = "redis_api_rest"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.29.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
